// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVF_hgD-iAvGmufadT3A_jBtPt3BBxv14',
    appId: '1:653124647916:web:074b61ac15c74f0aa19ec9',
    messagingSenderId: '653124647916',
    projectId: 'protexa-6d60c',
    authDomain: 'protexa-6d60c.firebaseapp.com',
    storageBucket: 'protexa-6d60c.firebasestorage.app',
    measurementId: 'G-CENZZSXY26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAljmEguaKMC6dILg4BN8d-V5R3-UKEj-0',
    appId: '1:653124647916:android:ab533d1953b5f2d6a19ec9',
    messagingSenderId: '653124647916',
    projectId: 'protexa-6d60c',
    storageBucket: 'protexa-6d60c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX3jW0qCTb7vlpvp9yRzoZFIpCITZ9BAU',
    appId: '1:653124647916:ios:5280a0efa1557214a19ec9',
    messagingSenderId: '653124647916',
    projectId: 'protexa-6d60c',
    storageBucket: 'protexa-6d60c.firebasestorage.app',
    iosBundleId: 'com.kodnix.protexa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX3jW0qCTb7vlpvp9yRzoZFIpCITZ9BAU',
    appId: '1:653124647916:ios:5280a0efa1557214a19ec9',
    messagingSenderId: '653124647916',
    projectId: 'protexa-6d60c',
    storageBucket: 'protexa-6d60c.firebasestorage.app',
    iosBundleId: 'com.kodnix.protexa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVF_hgD-iAvGmufadT3A_jBtPt3BBxv14',
    appId: '1:653124647916:web:aed8dee5e00495fea19ec9',
    messagingSenderId: '653124647916',
    projectId: 'protexa-6d60c',
    authDomain: 'protexa-6d60c.firebaseapp.com',
    storageBucket: 'protexa-6d60c.firebasestorage.app',
    measurementId: 'G-P2NZFTTH2S',
  );
}
